"""Step 14 - build the distributable archive (inha-tb-repo.tar.gz).

Ships everything needed to reproduce the pipeline from a clone: source, curated tables,
the gzipped ChEMBL pull, the receptor structure, figures, docs. Omits what is either
regenerable (fingerprint matrix, pose files, conformers) or large and already summarised
(the nine comparison PDB structures - their metadata lives in data/structure_meta.json).
"""
import fnmatch, os, tarfile

D = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
EXACT = {"data/fp_matrix.npy",          # 2.9 MB, regenerated by src/03
         "data/chembl_raw.json"}        # 6.6 MB, the .gz copy ships instead
DIRS = ("dock/pdbqt/", "dock/poses/", "dock/ligands/", "__pycache__/")
GLOBS = ("*.pyc", "*.log")
KEEP_STRUCT = "structures/4TZK.pdb"     # receptor input to src/05


def manifest(root):
    out = []
    for dirpath, dirs, files in os.walk(root):
        dirs[:] = [d for d in dirs if d not in ("__pycache__", ".ipynb_checkpoints")]
        for fn in files:
            rel = os.path.relpath(os.path.join(dirpath, fn), root)
            if rel in EXACT or rel.startswith(DIRS):
                continue
            if any(fnmatch.fnmatch(rel, g) for g in GLOBS):
                continue
            if rel.startswith("structures/") and rel.endswith(".pdb") and rel != KEEP_STRUCT:
                continue
            out.append(rel)
    return sorted(out)


def main():
    files = manifest(D)
    out = os.path.join(D, "..", "inha-tb-repo.tar.gz")
    with tarfile.open(out, "w:gz") as tf:
        for rel in files:
            tf.add(os.path.join(D, rel), arcname=f"inha-tb/{rel}")
    mb = os.path.getsize(out) / 1048576
    print(f"wrote {os.path.normpath(out)} - {len(files)} files, {mb:.1f} MB")
    for must in ("data/chembl_raw.json.gz", KEEP_STRUCT, "run_all.sh", "README.md",
                 "docs/METHODS.md", "docs/PROJECT_EXPLAINER_hinglish.pdf"):
        assert must in files, f"missing from archive: {must}"
    print("manifest check: required files present")


if __name__ == "__main__":
    main()
